version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db

    environment:
      POSTGRES_DB: job_market
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

  pipeline:
    build: .

    container_name: etl_pipeline

    depends_on:
      - db

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}